"""
Safety Event Module.

Defines the SafetyEvent data structure and provides canonical JSON
serialization for deterministic hashing.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Optional


def _generate_event_id() -> str:
    """Generate a unique event ID: evt-YYYYMMDD-HHMMSS-<hex4>."""
    now = datetime.now(timezone.utc)
    short_hex = uuid.uuid4().hex[:4]
    return f"evt-{now.strftime('%Y%m%d-%H%M%S')}-{short_hex}"


@dataclass
class SafetyEvent:
    """
    Represents a single safety event generated by the Decision Layer.

    This object is created *after* the safety action has already been executed.
    The blockchain layer receives this as a report of what happened, not as a
    command.
    """

    # Required fields
    timestamp: str
    tool_detected: bool
    mq2: int
    mq7: int
    temperature: float    # DHT11 temperature in °C
    humidity: float       # DHT11 relative humidity in %RH
    ir_detected: bool     # IR proximity sensor detection
    fan_state: str        # "ON" or "OFF"
    risk_score: float     # 0.0 – 1.0

    # Optional / auto-generated fields
    event_id: str = field(default_factory=_generate_event_id)
    risk_level: str = "LOW"          # LOW, MEDIUM, HIGH, CRITICAL
    action_taken: str = "NONE"       # FAN_ACTIVATED, FAN_DEACTIVATED, NONE
    sensor_node_id: str = "ESP32-NODE-01"

    # ---------------------------------------------------------------------- #
    #  Validation
    # ---------------------------------------------------------------------- #
    def __post_init__(self) -> None:
        if self.fan_state not in ("ON", "OFF"):
            raise ValueError(f"fan_state must be 'ON' or 'OFF', got '{self.fan_state}'")
        if not (0.0 <= self.risk_score <= 1.0):
            raise ValueError(f"risk_score must be in [0.0, 1.0], got {self.risk_score}")
        if not (-40.0 <= self.temperature <= 80.0):
            raise ValueError(f"temperature must be in [-40.0, 80.0], got {self.temperature}")
        if not (0.0 <= self.humidity <= 100.0):
            raise ValueError(f"humidity must be in [0.0, 100.0], got {self.humidity}")
        if self.risk_level not in ("LOW", "MEDIUM", "HIGH", "CRITICAL"):
            raise ValueError(f"Invalid risk_level: '{self.risk_level}'")
        if self.action_taken not in ("FAN_ACTIVATED", "FAN_DEACTIVATED", "NONE"):
            raise ValueError(f"Invalid action_taken: '{self.action_taken}'")

    # ---------------------------------------------------------------------- #
    #  Serialization
    # ---------------------------------------------------------------------- #
    def to_dict(self) -> dict:
        """Return the event as a plain dictionary."""
        return asdict(self)

    def to_canonical_json(self) -> str:
        """
        Return a deterministic canonical JSON string.

        Keys are sorted, separators use compact form (',', ':'), and no
        trailing whitespace is present.  This is the exact string that gets
        hashed by SHA-256.
        """
        return json.dumps(self.to_dict(), sort_keys=True, separators=(",", ":"))

    # ---------------------------------------------------------------------- #
    #  Factory
    # ---------------------------------------------------------------------- #
    @classmethod
    def from_dict(cls, data: dict) -> "SafetyEvent":
        """
        Create a SafetyEvent from a dictionary.

        Validates required fields and applies defaults for optional ones.
        """
        required = {"timestamp", "tool_detected", "mq2", "mq7", "temperature", "humidity", "ir_detected", "fan_state", "risk_score"}
        missing = required - set(data.keys())
        if missing:
            raise ValueError(f"Missing required fields: {missing}")

        return cls(
            event_id=data.get("event_id", _generate_event_id()),
            timestamp=data["timestamp"],
            tool_detected=data["tool_detected"],
            mq2=int(data["mq2"]),
            mq7=int(data["mq7"]),
            temperature=float(data["temperature"]),
            humidity=float(data["humidity"]),
            ir_detected=bool(data["ir_detected"]),
            fan_state=data["fan_state"],
            risk_score=float(data["risk_score"]),
            risk_level=data.get("risk_level", "LOW"),
            action_taken=data.get("action_taken", "NONE"),
            sensor_node_id=data.get("sensor_node_id", "ESP32-NODE-01"),
        )

    def __repr__(self) -> str:
        return (
            f"SafetyEvent(id={self.event_id}, ts={self.timestamp}, "
            f"risk={self.risk_score:.2f}, fan={self.fan_state}, "
            f"temp={self.temperature:.1f}°C, hum={self.humidity:.1f}%)"
        )
